// <auto-generated />
using JobApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JobApi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220826234008_models-v1")]
    partial class modelsv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("JobApi.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Department")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Position")
                        .HasColumnType("character varying(30)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("JobApi.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DueDate")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EmployeeDepartment")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("character varying(30)");

                    b.Property<string>("JobContent")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasColumnType("character varying(30)");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
